hw1: main.cpp
	g++ main.cpp -o hw3

test: hw3
	./hw3 6 bubble
	./hw3 8 bubble
	./hw3 10 bubble
	./hw3 12 bubble
	./hw3 6 heap
	./hw3 8 heap
	./hw3 10 heap
	./hw3 12 heap
	./hw3 14 heap
	./hw3 16 heap
