hw1: main.cpp
	g++ main.cpp -o hw3

test: hw3
	time ./hw3 6 bubble
	time ./hw3 8 bubble
	time ./hw3 10 bubble
	time ./hw3 12 bubble
	time ./hw3 14 bubble
	time ./hw3 16 bubble
	time ./hw3 6 heap
	time ./hw3 8 heap
	time ./hw3 10 heap
	time ./hw3 12 heap
	time ./hw3 14 heap
	time ./hw3 16 heap
